config/routes.rb
Rails.application.routes.draw do
  resources :foods
  resources :menus
  

  # [method] '[insert model]/[insert crud], to: '[insert controller]#[insert method]'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
    belongs_to :menu
end

app/models/menu.rb
class Menu < ApplicationRecord
has_many :foods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def new
    @menu = Menu.new
  end

  def index
    @menus = Menu.all
  end

  def show
    @menu = Menu.find_by(params [:id])
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThanksgivingDinner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menus/edit.html.erb
<h1>Menu#edit</h1>
<p>Find me in app/views/menu/edit.html.erb</p>

app/views/menus/index.html.erb
<h1>Menu#index</h1>
<% @menus.each do |i| %>
  <%= link_to i.name, menu_path(i) %>
<%end%>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= form_for @menu do |f| %>
    <%= f.label :appetizer %>
    <%= f.text_field :appetizer %>
    <%= f.label :entree %>
    <%= f.text_field :entree %>
    <%= f.label :drinks %>
    <%= f.text_field :drinks %>
    <%= f.label :dessert %>
    <%= f.text_field :dessert %>
    <%= f.submit %>
<%end%>

  

app/views/menus/show.html.erb
<h1>This Menu/h1>
<% @menu.each do |i| %>
    <%= i.appetizer %>
    <%= i.entree %>
    <%= i.drinks %>
    <%= i.dessert %>
 <%end%>